// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repositories

import (
	"context"
)

type Querier interface {
	CreateMasterPromo(ctx context.Context, arg CreateMasterPromoParams) (MasterPromo, error)
	CreateMasterPromoCondition3pl(ctx context.Context, arg CreateMasterPromoCondition3plParams) (MasterPromoCondition3pl, error)
	CreateMasterPromoConditionPlatform(ctx context.Context, arg CreateMasterPromoConditionPlatformParams) (MasterPromoConditionPlatform, error)
	CreateMasterPromoConditionProduct(ctx context.Context, arg CreateMasterPromoConditionProductParams) (MasterPromoConditionProduct, error)
	CreateMasterPromoProductBenefit(ctx context.Context, arg CreateMasterPromoProductBenefitParams) (MasterPromoProductBenefit, error)
	CreateMasterPromoVoucher(ctx context.Context, arg CreateMasterPromoVoucherParams) (MasterPromoVoucher, error)
	FindAllActiveMasterPromoToday(ctx context.Context) ([]MasterPromo, error)
	GetMasterPromoById(ctx context.Context, promoid int64) (MasterPromo, error)
	GetMasterPromoCondition3PlBy(ctx context.Context, arg GetMasterPromoCondition3PlByParams) (MasterPromoCondition3pl, error)
	GetMasterPromoConditionPlatformBy(ctx context.Context, arg GetMasterPromoConditionPlatformByParams) (MasterPromoConditionPlatform, error)
	GetMasterPromoConditionProductBy(ctx context.Context, arg GetMasterPromoConditionProductByParams) (MasterPromoConditionProduct, error)
	GetMasterPromoProductBenefitBy(ctx context.Context, arg GetMasterPromoProductBenefitByParams) (MasterPromoProductBenefit, error)
	GetMasterPromoVoucherBy(ctx context.Context, arg GetMasterPromoVoucherByParams) (MasterPromoVoucher, error)
}

var _ Querier = (*Queries)(nil)
